### PR TITLE
Add verifyNoInteractions, mark verifyZeroInteractions as deprecated

### PR DESCRIPTION
**Pull request by andreprinz**
Solved these 2 issues:

Possible after https://github.com/mockito/mockito-kotlin/issues/355
Fixes https://github.com/mockito/mockito-kotlin/issues/383

### CODE REVIEW

**Comment by TWiStErRob** [comment]
@andreprinz @mockitoguy can we get this over the line please?

**Comment by andreprinz** [comment]
> @andreprinz @mockitoguy can we get this over the line please?

pull request is rebased

**Review by TimvdLippe — APPROVED** [review]
Yup this makes sense to me!

**Comment by TimvdLippe** [comment]
Apologies this took so long! Merged the PR 😄

**Pull request merged**
