### PR TITLE
#478 Upgrade Mockito 

### PR DESCRIPTION
**Pull request by lukas-krecan**

### CODE REVIEW

**Comment by lukas-krecan** [comment]
It's not compatible with older Mockito versions so it should be a major version release.

**Comment by emartynov** [comment]
Is it for #474 ?

**Comment by lukas-krecan** [comment]
> Is it for #474 ?

Yes, and https://github.com/mockito/mockito-kotlin/issues/478

**Comment by lukas-krecan** [comment]
Sorry, I do not understand. Which tests do you mean?

**Comment by TimvdLippe** [comment]
Mockito 5 made breaking changes to varargs matchers. I expected that to have consequences for Kotlin as well. However, I see little to no changes in the regression test suite of `mockito-kotlin` in this PR. Does that mean that these breaking changes were not relevant for Kotlin folks, or that we are missing test suite coverage?

**Comment by lukas-krecan** [comment]
> Does that mean that these breaking changes were not relevant for Kotlin folks, or that we are missing test suite coverage?

I guess both. The only impacted method here is `anyVararg`, I had to add a tests as I did not trust the current coverage. Moreover, in Kotlin you can't just use an array in vararg, you have to use the `method(*array)` syntax. Maybe it helped.

But I am a first-time contributor to this library, so taky me with a huge grain of salt.

**Comment by lukas-krecan** [comment]
Just for completenes, changing the signature to `fun <T : Any> anyVararg(clazz: KClass<T>): Array<T>` and using it like this `method(*anyVararg())` might be cleaner, but would complicate the migration path without much additional value.

**Review by TimvdLippe — APPROVED** [review]
Sounds good to me, thanks!

**Pull request merged**
